name: MySQL Admin

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "smoke"
        type: choice
        options:
          - smoke
          - provision
          - scale-up
          - scale-down
          - stop
          - start
          - delete
          - migrate
      run_migrations:
        description: "Run php artisan migrate --force after 'provision'"
        required: false
        default: "false"
        type: choice
        options: ["true","false"]
      maintenance_mode:
        description: "Put Laravel in maintenance mode during 'migrate'"
        required: false
        default: "true"
        type: choice
        options: ["true","false"]

concurrency:
  group: mysql-admin-${{ github.ref }}
  cancel-in-progress: false

env:
  AZURE_RG: laravel-rg
  ACA_NAME: laravel-aca
  # Adjust if needed:
  MYSQL_INFRA_DIR: infra/mysql

permissions:
  id-token: write   # for azure/login OIDC
  contents: read

jobs:
  smoke:
    if: ${{ github.event.inputs.action == 'smoke' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check MySQL RP registration (read-only)
        run: |
          set -euo pipefail
          STATE=$(az provider show -n Microsoft.DBforMySQL --query registrationState -o tsv || echo "Unknown")
          echo "Microsoft.DBforMySQL registrationState: $STATE"
          if [ "$STATE" != "Registered" ]; then
            echo "❌ Microsoft.DBforMySQL is not Registered at the subscription. Please register it once (Portal or CLI) and rerun."
            exit 1
          fi

      - name: Verify resource group and Container Apps env
        run: |
          set -euo pipefail
          az group show -n "$AZURE_RG" -o table
          az containerapp env list -g "$AZURE_RG" -o table || true

      - name: Show Container App and public URL
        run: |
          set -euo pipefail
          az containerapp show -g "$AZURE_RG" -n "$ACA_NAME" \
            --query "{name:name,ingress:configuration.ingress.fqdn,activeRev:properties.latestRevisionName}" -o yaml || true

      - name: List Container App outbound IPs
        run: |
          set -euo pipefail
          az containerapp show -g "$AZURE_RG" -n "$ACA_NAME" \
            --query "properties.outboundIpAddresses" -o tsv || true

  provision:
    if: ${{ github.event.inputs.action == 'provision' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check MySQL RP registration (read-only)
        run: |
          set -euo pipefail
          STATE=$(az provider show -n Microsoft.DBforMySQL --query registrationState -o tsv || echo "Unknown")
          echo "Microsoft.DBforMySQL registrationState: $STATE"
          if [ "$STATE" != "Registered" ]; then
            echo "❌ Microsoft.DBforMySQL is not Registered at the subscription. Please register it once (Portal or CLI) and rerun."
            exit 1
          fi

      - name: Provision MySQL Flexible Server + DB + user + firewall + secrets
        env:
          # required by your script
          MYSQL_ADMIN_PASSWORD: ${{ secrets.MYSQL_ADMIN_PASSWORD }}
          MYSQL_APP_PASSWORD:   ${{ secrets.MYSQL_APP_PASSWORD }}
          # known values for your environment (adjust if your script uses different var names)
          MYSQL_SERVER_NAME: fest-db
          MYSQL_DB_NAME:     laravel
          MYSQL_APP_USER:    appuser
          AZURE_RG:          ${{ env.AZURE_RG }}
        run: |
          set -euo pipefail
          bash "$MYSQL_INFRA_DIR/provision-mysql.sh"

      # ✅ Optional: run Laravel migrations right after provisioning
      - name: Run migrations in Container App
        if: ${{ github.event.inputs.run_migrations == 'true' }}
        run: |
          set -euo pipefail
          # Ensure an active revision exists (no-op if already healthy)
          az containerapp revision list \
            --resource-group "$AZURE_RG" \
            --name "$ACA_NAME" \
            --query "[?properties.active==\`true\`].name" -o tsv
          # Wrap each exec with a TTY to avoid CI ioctl error
          script -q -c "az containerapp exec --resource-group \"$AZURE_RG\" --name \"$ACA_NAME\" --command 'php artisan migrate --force'" /dev/null
          script -q -c "az containerapp exec --resource-group \"$AZURE_RG\" --name \"$ACA_NAME\" --command 'php artisan config:clear'" /dev/null
          script -q -c "az containerapp exec --resource-group \"$AZURE_RG\" --name \"$ACA_NAME\" --command 'php artisan cache:clear'" /dev/null
          script -q -c "az containerapp exec --resource-group \"$AZURE_RG\" --name \"$ACA_NAME\" --command 'php artisan route:cache'" /dev/null
          script -q -c "az containerapp exec --resource-group \"$AZURE_RG\" --name \"$ACA_NAME\" --command 'php artisan event:cache'" /dev/null

  scale-up:
    if: ${{ github.event.inputs.action == 'scale-up' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Scale MySQL up (GP 2 vCPU / 8 GB)
        run: |
          set -euo pipefail
          bash "$MYSQL_INFRA_DIR/scale-up.sh"

  scale-down:
    if: ${{ github.event.inputs.action == 'scale-down' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Scale MySQL down (Burstable smallest available)
        run: |
          set -euo pipefail
          bash "$MYSQL_INFRA_DIR/scale-down.sh"

  stop:
    if: ${{ github.event.inputs.action == 'stop' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Stop MySQL Flexible Server
        run: |
          set -euo pipefail
          bash "$MYSQL_INFRA_DIR/stop-start-mysql.sh" stop

  start:
    if: ${{ github.event.inputs.action == 'start' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Start MySQL Flexible Server
        run: |
          set -euo pipefail
          bash "$MYSQL_INFRA_DIR/stop-start-mysql.sh" start

  delete:
    if: ${{ github.event.inputs.action == 'delete' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Delete MySQL Flexible Server (idempotent)
        run: |
          set -euo pipefail
          bash "$MYSQL_INFRA_DIR/delete-mysql.sh"

  migrate:
    if: ${{ github.event.inputs.action == 'migrate' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Install MySQL client + OpenSSH
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client openssh-client jq

      - name: Run database migration script
        env:
          # Repo env
          AZURE_RG: ${{ env.AZURE_RG }}
          ACA_NAME: ${{ env.ACA_NAME }}

          # Cloudways (source)
          CW_DB_NAME:     ${{ secrets.CW_DB_NAME }}      # gthewnsykf
          CW_DB_USER:     ${{ secrets.CW_DB_USER }}      # gthewnsykf
          CW_DB_PASSWORD: ${{ secrets.CW_DB_PASSWORD }}
          CW_SSH_HOST:    ${{ secrets.CW_SSH_HOST }}     # Cloudways server IP
          CW_SSH_USER:    ${{ secrets.CW_SSH_USER }}     # master SSH user
          CW_SSH_KEY:     ${{ secrets.CW_SSH_KEY }}      # private key (PEM)

          # Azure (target)
          MYSQL_APP_PASSWORD: ${{ secrets.MYSQL_APP_PASSWORD }}

          # Toggle via workflow input
          MAINTENANCE_MODE: ${{ github.event.inputs.maintenance_mode }}

          # Optional overrides (else script defaults)
          # AZ_MYSQL_SERVER_NAME: fest-db
          # AZ_MYSQL_DB: laravel
          # AZ_MYSQL_USER: appuser
        run: bash "$MYSQL_INFRA_DIR/migrate.sh"
